parameters:
#    mefi_info_dump.example.class: Mefi\InfoDumpBundle\Example
  infodump.usernames: 'MefiInfoDumpBundle:Usernames'

services:

  infodump.usernames.data:
    class: Mefi\InfoDumpBundle\Data\UsernamesData
    arguments: [ @doctrine.orm.entity_manager, true, 3600 ]

  infodump.askmeposts.data:
    class: Mefi\InfoDumpBundle\Data\AskMePostsData
    arguments: [ @doctrine.orm.entity_manager, true, 3600 ]
