parameters:
#    mefi_info_dump.example.class: Mefi\InfoDumpBundle\Example
  infodump.usernames: 'MefiInfoDumpBundle:Usernames'

services:

  infodump.singletable.data:
    class: Mefi\InfoDumpBundle\Data\UsernamesData
    arguments: [ @doctrine.orm.entity_manager, true, 3600 ]
