parameters:
#    mefi_info_dump.example.class: Mefi\InfoDumpBundle\Example

services:
#    mefi_info_dump.example:
#        class: %mefi_info_dump.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
